name: Java CI/CD

# События
on:
  push:                # Запускается при пуше в указанные ветки
    branches:
      - master         # Следим за веткой master
  pull_request:        # Запускается при pull request
    branches:
      - master         # Следим за PR в ветку master

# Описание задач
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }} # Платформы для выполнения
    strategy:
      matrix:          # ОС и версии Java
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [17] # Старые версии не вставлял
      fail-fast: false # Продолжить выполнение, если какая нибудь ОС упадёт(для отладки)

    # Шаги выполнения задачи
    steps:
      # Клонирование кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # Используем Temurin JDK

      # Проверка версии Maven (опционально/для отладки)
      - name: Check Maven version
        run: mvn -v

      # Установка Maven для Linux и MacOS
      - name: Install Maven (Linux/Mac)
        if: runner.os != 'Windows'
        run: |
          curl -o apache-maven-3.8.8-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          tar -xvzf apache-maven-3.8.8-bin.tar.gz
          sudo mv apache-maven-3.8.8 /usr/local/apache-maven
          echo "export PATH=/usr/local/apache-maven/bin:$PATH" >> $GITHUB_ENV

      # Установка Maven для Windows
      - name: Install Maven (Windows)
        if: runner.os == 'Windows'
        run: |
          curl -o apache-maven-3.8.8-bin.zip https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
          tar -xf apache-maven-3.8.8-bin.zip
          move apache-maven-3.8.8 "C:\apache-maven"
          echo "C:\apache-maven\bin" >> $GITHUB_ENV

      # Очистка локального репозитория Maven
      - name: Clean local repository
        run: mvn dependency:purge-local-repository

      # Сборка Maven проекта
      - name: Build project
        run: mvn clean install

      # Запуск Maven тестов
      - name: Run tests
        run: mvn test

  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest # Деплой выполняем на Linux
    needs: build # Зависимость от успешной сборки
    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Деплой через SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}              # IP-адрес сервера
          username: ${{ secrets.SSH_USER }}          # Имя пользователя
          key: ${{ secrets.SSH_PRIVATE_KEY }}        # Приватный ключ для подключения
          port: 22                                   # Порт SSH (по умолчанию 22)
          script: |
            cd /path/to/deployment                   # Путь к директории деплоя на сервере
            git pull origin master                   # Обновление с репозитория
            ./restart.sh                             # Перезапуск приложения