name: Java CI/CD

# События
on:
  push:                # Запускается при пуше в указанные ветки
    branches:
      - master         # Следим за веткой master
  pull_request:        # Запускается при pull request
    branches:
      - master         # Следим за pull request в ветку master

# Описание задач
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }} # Платформы для выполнения
    strategy:
      matrix:          # ОС и версии Java
        os: [ubuntu-22.04, windows-latest, macos-latest]
        java-version: [17]
      fail-fast: false # Продолжить выполнение, даже если одна ОС упадёт

    # Шаги выполнения задачи
    steps:
      # Шаг 1: Клонирование кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin' # Используем Temurin JDK

      - name: Check Maven version
        run: mvn -v

      - name: Install Maven
        run: |
          curl -o apache-maven-3.8.8-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
          tar -xvzf apache-maven-3.8.8-bin.tar.gz
          sudo mv apache-maven-3.8.8 /usr/local/apache-maven
          echo "export PATH=/usr/local/apache-maven/bin:$PATH" >> $GITHUB_ENV

      - name: Print system info
        run: |
          uname -a
          java -version
          mvn -v

      - name: Clean local repository
        run: mvn dependency:purge-local-repository

      # Шаг 3: Сборка Maven проекта
      - name: Build project
        run: mvn clean install
        continue-on-error: ${{ matrix.os == 'macos-latest' }}

      # Шаг 4: Запуск Maven тестов
      - name: Run tests
        run: mvn test
        continue-on-error: ${{ matrix.os == 'macos-latest' }}

  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Деплой через SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}              # IP-адрес моей виртуалки
          username: ${{ secrets.SSH_USER }}          # Имя пользователя на моей виртуалке
          key: ${{ secrets.SSH_PRIVATE_KEY }}        # Приватный ключ для подключения
          port: 22                                   # Порт SSH (по умолчанию 22)
          script: |
            cd /path/to/deployment                   # Путь к директории деплоя на сервере
            git pull origin master                   # Обновление с репозитория
            ./restart.sh                             # Перезапуск приложения
